"""Extract field-contract matrix from the configured source Markdown."""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

from tool_config import ToolConfig


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SOURCE_NAME = "audit_sacrm190_pdf.md"
DEFAULT_SOURCE = (SCRIPT_DIR / ".." / "ref" / DEFAULT_SOURCE_NAME).resolve()
DEFAULT_OUTPUT_DIR = (SCRIPT_DIR / ".." / "outputs").resolve()
DEFAULT_OUTPUT_NAME = "SACRM190-欄位契約矩陣.md"
DEFAULT_TITLE_ENV_KEY = "TOOL_FIELD_MATRIX_TITLE"
DEFAULT_SOURCE_ENV_KEY = "TOOL_FIELD_MATRIX_SOURCE"
DEFAULT_OUTPUT_FILE_ENV_KEY = "TOOL_FIELD_MATRIX_OUTPUT"
DEFAULT_OUTPUT_DIR_ENV_KEY = "TOOL_FIELD_MATRIX_OUTPUT_DIR"
SOURCE_FIELD_MATRIX_TITLE = "FS-SACRM190-PB客戶盡職調查功能 - 欄位契約矩陣（抽取版）"


def _env_value(settings: ToolConfig, key: str, default: str) -> str:
    try:
        return settings.value(key)
    except ValueError:
        return default


def _env_path(settings: ToolConfig, key: str, default: Path) -> Path:
    try:
        return settings.path(key)
    except ValueError:
        return default


def normalize_header(value: str) -> str:
    if not value:
        return ""
    return re.sub(r"\s+", "", value.replace("<br>", "").strip())


def normalize_cell(value: str) -> str:
    if not value:
        return ""
    v = value.replace("<br>", " ").replace("\r", " ").replace("\n", " ")
    v = re.sub(r"\s+", " ", v).strip()
    return v.replace("|", "\\|")


def parse_table_line(line: str) -> list[str]:
    line = line.strip()
    if not line.startswith("|"):
        return []
    return [cell.strip() for cell in line.strip("|").split("|")]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract field-contract matrix table rows.")
    settings = ToolConfig()
    configured_source = _env_path(settings, DEFAULT_SOURCE_ENV_KEY, DEFAULT_SOURCE)
    configured_output_dir = _env_path(settings, DEFAULT_OUTPUT_DIR_ENV_KEY, DEFAULT_OUTPUT_DIR)
    configured_output = _env_path(settings, DEFAULT_OUTPUT_FILE_ENV_KEY, configured_output_dir / DEFAULT_OUTPUT_NAME)
    configured_title = _env_value(settings, DEFAULT_TITLE_ENV_KEY, SOURCE_FIELD_MATRIX_TITLE)
    parser.add_argument(
        "--source-markdown",
        "-s",
        default=str(configured_source),
        help="Source markdown file generated by PDF extraction.",
    )
    parser.add_argument(
        "--output-markdown",
        "-o",
        default=str(configured_output),
        help="Output markdown file path for extracted matrix.",
    )
    parser.add_argument(
        "--title",
        default=configured_title,
        help="Output title line; can be set by environment TOOL_FIELD_MATRIX_TITLE",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_path = Path(args.source_markdown)
    output_path = Path(args.output_markdown)

    line_list = source_path.read_text(encoding="utf-8").splitlines()

    page_no = ""
    section = ""
    entries: list[dict[str, str]] = []

    i = 0
    while i < len(line_list):
        line = line_list[i]

        if re.match(r"^##\s+PDF page\s+\d+", line):
            page_no = re.sub(r"^##\s+PDF page\s+", "", line).strip()
            i += 1
            continue

        if re.match(r"^##\s+(?!PDF page\s+).+", line):
            section = line.lstrip("#").strip()
            i += 1
            continue

        if re.match(r"^###\s+Table\s+\d+", line):
            j = i + 1
            while j < len(line_list) and not line_list[j].strip():
                j += 1
            if j >= len(line_list):
                i += 1
                continue

            table_lines: list[str] = []
            while j < len(line_list) and line_list[j].strip().startswith("|"):
                table_lines.append(line_list[j])
                j += 1
            i = j - 1

            if len(table_lines) < 3:
                i += 1
                continue

            header_index = -1
            for row_idx, row_text in enumerate(table_lines):
                cells = parse_table_line(row_text)
                if not cells:
                    continue
                normalized = [normalize_header(cell) for cell in cells]
                if any("欄位名稱" in cell for cell in normalized) and any(
                    "說明" in cell for cell in normalized
                ):
                    header_index = row_idx
                    break

            if header_index < 0:
                i += 1
                continue

            header = parse_table_line(table_lines[header_index])
            if not header:
                i += 1
                continue

            header_map: dict[str, int] = {
                normalize_header(col): idx for idx, col in enumerate(header)
            }
            if "欄位名稱" not in header_map:
                i += 1
                continue

            field_idx = header_map["欄位名稱"]
            format_idx = header_map.get("欄位格式", -1)
            api_idx = header_map.get(
                "資料欄位名稱(API對應名稱/程式對應名稱)",
                header_map.get("資料欄位名稱", -1),
            )
            desc_idx = header_map.get("說明", -1)

            data_start = header_index + 1
            while (
                data_start < len(table_lines)
                and re.match(r"^\|\s*[-: ]+\|\s*$", table_lines[data_start])
            ):
                data_start += 1

            for row_idx in range(data_start, len(table_lines)):
                row = parse_table_line(table_lines[row_idx])
                if len(row) <= field_idx:
                    continue

                field = normalize_cell(row[field_idx])
                if not field or field == "欄位名稱" or field in {"A", "B", "C", "D", "E", "F"}:
                    continue
                if re.fullmatch(r"[A-Z]", field):
                    continue

                entries.append(
                    {
                        "Page": page_no or "未定位",
                        "Section": section or "未命名區段",
                        "Field": field,
                        "Format": normalize_cell(row[format_idx]) if format_idx >= 0 and len(row) > format_idx else "",
                        "ApiField": normalize_cell(row[api_idx]) if api_idx >= 0 and len(row) > api_idx else "",
                        "Description": normalize_cell(row[desc_idx]) if desc_idx >= 0 and len(row) > desc_idx else "",
                    }
                )

            i += 1
            continue

        i += 1

    lines_out: list[str] = []
    lines_out.append(f"# {args.title}")
    lines_out.append("")
    lines_out.append("## 來源")
    lines_out.append(f"- 本檔案由 [{source_path.name}]({source_path.name}) 的欄位表格萃取而來。")
    lines_out.append("- 萃取條件：欄位表頭含 `欄位名稱`、`欄位格式`、`說明`。")
    lines_out.append("")
    lines_out.append("| 頁碼 | 區段 | 欄位名稱 | 欄位格式 | 資料欄位名稱 | 說明 |")
    lines_out.append("| --- | --- | --- | --- | --- | --- |")

    for item in entries:
        lines_out.append(
            f"| {item['Page']} | {item['Section']} | {item['Field']} | {item['Format']} | {item['ApiField']} | {item['Description']} |"
        )

    lines_out.append("")
    lines_out.append("## 來源統計")
    lines_out.append(f"- 抽取欄位數：{len(entries)}")

    output_path.write_text("\n".join(lines_out) + "\n", encoding="utf-8")
    print(f"抽取完成：{len(entries)} 筆，輸出到 {output_path}")


if __name__ == "__main__":
    main()
